%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

# System.SaveAtlasToFile: "map_for_stereo_from_20240603_120008_12_to_20240603_120459_99_merge_SlowRun_SlowBag_ZED2"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 1071.58
Camera1.fy: 1072.15
Camera1.cx: 955.33
Camera1.cy: 555.983

Camera1.k1: -0.0519091
Camera1.k2: 0.0250782
Camera1.p1: 0.000533807
Camera1.p2: 0.000117517
Camera1.k3: -0.0101723

Camera2.fx: 1067.61
Camera2.fy: 1068.32
Camera2.cx: 964.59
Camera2.cy: 555.556

Camera2.k1: -0.057705696896734
Camera2.k2: 0.086955444511364
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

Camera.width: 1920
Camera.height: 1080


# Camera frames per second 
Camera.fps: 8


# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# 0: disable loop closure, 1: enable loop closure
System.LoopClosing: 1


# Close/Far threshold. Baseline times.
Stereo.ThDepth: 65.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.99996212, -0.00133436,  0.00860078, -0.119729,
          0.00134459,  0.99999839, -0.00118413, -0.000135398,
          -0.00859918,  0.00119565,  0.99996231, 0.000681149,
          0.0,0.0,0.0,1.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

